---
title: "Data Import"
author: "Ava Hamilton"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

#Load in litter Dataset
```{r}
##reads in dataset
##Relative Path
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")

## clean names
litters_data = janitor::clean_names(litters_data)
```


## Read in pups dataset
```{r}
## read in next dataset
#relative
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
#absolute
pups_data = read_csv(file = "/Users/avahamilton/Dropbox/Biostat MS/Data Science I/DataWrangling1/data_import_examples/FAS_pups.csv")

## clean names
pups_data = janitor::clean_names(pups_data)
```


### play with column parsing 

```{r}
litters_data = read_csv(file = "./data_import_examples//FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
```


##Read in excel file
```{r}
#using readxl package

mlb11_data = read_excel(path = "./data_import_examples/mlb11.xlsx")

```

##Read in SAS
```{r}
pulse_data = haven::read_sas(data_file = "./data_import_examples/public_pulse_data.sas7bdat")
```





